### ISSUE TITLE
cpm_kernels_cuda问题

### ISSUE THREAD

**Issue by misska1** [OpenBMB/cpm_kernels#2]
在容器里运行bminf的时候报错cpm_kernels的问题，应该是搜不到cuda？

Traceback (most recent call last):
  File "generate_cpm1.py", line 32, in <module>
    main()
  File "generate_cpm1.py", line 27, in main
    cpm1 = bminf.models.CPM1()
  File "/usr/local/lib/python3.7/site-packages/bminf/models/cpm1.py", line 41, in __init__
    device_idx = cudart.cudaGetDevice()
  File "/usr/local/lib/python3.7/site-packages/cpm_kernels/library/base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cudart is not initialized

**Comment by misska1** [comment]
nvidia-docker run -it -d -v $(pwd):/workspace  --gpus all rct-docker-registry.cn-zhangjiakou.cr.aliyuncs.com/algorithm/torch_1.9_cuda11:ltp bash

**Comment by a710128** [comment]
可以提供一下容器内nvidia-smi输出以及cuda版本吗？

**Comment by misska1** [comment]
<img width="649" alt="截屏2022-03-08 下午2 34 24" src="https://user-images.githubusercontent.com/22286006/157180493-a6f541e0-c392-4842-a704-708d272a4b98.png">

**Comment by misska1** [comment]
torch.cuda.is_available()也是可以的

**Comment by a710128** [comment]
可以尝试设置 `CUDA_PATH` 环境变量为容器内 cuda 的安装路径
